# 文档字段提取指令配置
# 用于指导LLM如何从不同类型的文档中提取字段信息

version: "1.0"
last_updated: "2024-01-15T10:30:00Z"

instructions:
  invoice: #发票
    instruction: |
      您正在从发票文档中提取信息。请重点关注：
      - 财务金额和总额（含税金额、税额等）
      - 发票日期和开票日期
      - 购买方和销售方信息
      - 发票号码和参考代码
      - 税务信息和税率
      - 商品或服务描述
      - 付款方式和条件
      
      请仔细识别发票上的所有关键信息，确保提取的准确性。

  lease: #租赁协议
    instruction: |
      您正在从租赁协议中提取信息。请重点关注：
      - 物业地址和详细位置信息
      - 租赁期限和起止日期
      - 租金金额和付款计划
      - 押金和安全要求
      - 租赁面积和使用条款
      - 免租期和优惠条件
      - 法律条款和违约责任
      - 签署日期和合同编号
      
      请仔细分析协议条款，确保提取所有重要的租赁信息。

  amendment: #变更/解除协议
    instruction: |
      您正在从变更/解除协议中提取信息。请重点关注：
      - 原协议的基本信息（合同编号、签署日期等）
      - 变更的具体内容和条款
      - 涉及的时间段和期限调整
      - 变更前后的差异对比
      - 新的租金或费用标准
      - 生效日期和适用期间
      - 签署日期和各方确认
      
      请仔细识别变更的具体内容，确保准确提取所有修改信息。

  bill: #账单
    instruction: |
      您正在从账单文档中提取信息。请重点关注：
      - 账单金额和费用明细
      - 账单周期和计费期间
      - 付款方和收款方信息
      - 账单编号和参考信息
      - 付款截止日期
      - 费用项目和分类
      - 预收或补缴情况
      - 账单发出日期
      
      请仔细核对账单上的所有财务信息，确保提取的准确性。

  bank_receipt: #银行回单
    instruction: |
      您正在从银行回单中提取信息。请重点关注：
      - 转账金额和交易类型
      - 交易日期和时间
      - 付款方和收款方信息
      - 银行流水号和参考信息
      - 账户信息和余额
      - 交易状态和结果
      - 备注和摘要信息
      - 手续费和其他费用
      
      请仔细识别回单上的所有交易信息，确保提取的准确性。

# 默认指令（用于未识别的文档类型）
default:
  instruction: |
    您正在从文档中提取信息。请仔细分析文档内容，提取所有可见的关键信息。
    重点关注：
    - 日期信息
    - 金额和数字
    - 名称和地址
    - 编号和代码
    - 其他重要信息
    
    请尽可能准确地提取文档中的所有相关信息。
