# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon*\x89\x01\n\x08\x46ileType\x12\x15\n\x11\x46ILE_TYPE_UNKNOWN\x10\x00\x12\x15\n\x11\x46ILE_TYPE_INVOICE\x10\x01\x12\x1c\n\x18\x46ILE_TYPE_BANK_STATEMENT\x10\x02\x12\x12\n\x0e\x46ILE_TYPE_BILL\x10\x03\x12\x1d\n\x19\x46ILE_TYPE_LEASE_AGREEMENT\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILETYPE']._serialized_start=25
  _globals['_FILETYPE']._serialized_end=162
# @@protoc_insertion_point(module_scope)
